#spring.datasource.url=jdbc:h2:mem:testdb

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_422a7800be4c44e
    username: bff884f66dcfae
    password: 94998f60
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update