logging:
  level:
    org:
      springframework:
        security: INFO

spring:
  mail:
    host: localhost
    port: 99999
    username: test
    password: test
    sender: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


external-apis:
  confirm-email: 'https://dividend-portfolio.netlify.app/confirm'
  reset-password-email: 'https://dividend-portfolio.netlify.app/confirm'

google:
  recaptcha:
    key:
      secret-key: test
      verify-url: https://www.google.com/recaptcha/api/siteverify

