logging:
  level:
    org:
      springframework:
        security: INFO

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: localhost
    port: 587
    username: dividend-portfolio@example.com
    password: test
    sender: dividend-portfolio@example.com
  datasource:
    url: jdbc:mysql://localhost:3306/DIV_INV
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true


external-apis:
  confirm-email: 'https://dividend-portfolio.netlify.app/confirm'
  reset-password-email: 'https://dividend-portfolio.netlify.app/login'

