
spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    sender: ${MAIL_FROM}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

auth:
  confirmation-token-expiration-minutes: 15
  new-password-token-expiration-minutes: 15

caching:
  spring:
    dividend-history: 43200000
    price-history: 43200000

external-apis:
  yahoofinance-cashflow: https://query1.finance.yahoo.com/v10/finance/quoteSummary/{symbol}?modules=cashflowStatementHistory
  yahoofinance-cashflow-quarterly: https://query1.finance.yahoo.com/v10/finance/quoteSummary/{symbol}?modules=cashflowStatementHistoryQuarterly
  yahoofinance-income-statements: https://query1.finance.yahoo.com/v11/finance/quoteSummary/{symbol}?modules=incomeStatementHistory
  yahoofinance-income-statements-quarterly: https://query1.finance.yahoo.com/v11/finance/quoteSummary/{symbol}?modules=incomeStatementHistoryQuarterly
  yahoofinance-balance-sheet: https://query1.finance.yahoo.com/v11/finance/quoteSummary/{symbol}?modules=balanceSheetHistory
  yahoofinance-balance-sheet-quarterly: https://query1.finance.yahoo.com/v11/finance/quoteSummary/{symbol}?modules=balanceSheetHistoryQuarterly
  confirm-email: ${CONFIRMATION_EMAIL_REDIRECT}

google:
  recaptcha:
    key:
      verify-url: https://www.google.com/recaptcha/api/siteverify
      secret-key: ${RECAPTCHA_SECRET}