package com.adamnagyan.yahoofinancewebapi.exceptions;

public enum ErrorCode {

	OO_INVALID_ARGUMENT_ERROR, OO_GENERAL_ERROR, OO_USER_ALREADY_EXISTS, OO_INVALID_CREDENTIALS, OO_DISABLED_USER,
	OO_USER_NOT_FOUND, OO_USER_ALREADY_ENABLED, OO_CONFIRMATION_TOKEN_NOT_FOUND, OO_CONFIRMATION_TOKEN_EXPIRED,
	OO_RECAPTCHA_ERROR, OO_MAIL_SENDING_ERROR, OO_PERMISSION_DENIED

}
